# Generated by Django 5.2.4 on 2025-08-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='parent_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
